spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1835
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  cache:
    redis:
      time-to-live: 300000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
jwt:
 secret: 21DRzqosrLa2a+hGwHmjrmlp7IrfaW3Lsdwl3wsLWto= # Replace with a secure key
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    root: INFO
    com.jktech: DEBUG
    com.main: DEBUG
    org.apache.tika: DEBUG
    org.springframework.batch: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.amqp: DEBUG